# Generated by Django 3.2.7 on 2021-10-03 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='text',
            new_name='description',
        ),
    ]
